name: 功能建议
description: 分享你想改善的使用体验
title: "[建议] "
body:
  - type: input
    id: version
    attributes:
      label: 软件版本与系统
  - type: textarea
    id: problem
    attributes:
      label: 你想解决什么问题
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 你希望怎样操作
    validations:
      required: true
